##################################################################################################
# Loadgen
##################################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  namespace: beachshirts
  labels:
    app: loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - name: loadgen
        image: vikramraman/loadgen
