server:
  applicationConnectors:
  - type: http
    port: 50050
  adminConnectors:
  - type: http
    port: 50150

stylingPort: 50051
deliveryPort: 50052
stylingHost: "styling.beachshirts-agent.svc.cluster.local"
deliveryHost: "delivery.beachshirts-agent.svc.cluster.local"
