apiVersion: v1
kind: Service
metadata:
  name: shopping
  namespace: beachshirts-agent
  labels:
    app: shopping
spec:
  ports:
    - targetPort: 50050
      port: 50050
      name: http
  selector:
      app: shopping
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shopping
  namespace: beachshirts-agent
  labels:
    app: beachshirts-agent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shopping
    spec:
      containers:
        - name: shopping
          image: vikramraman/shopping-agent:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 50050
